FROM python:3.6

# Setup Nodejs v8.x
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - \
  && apt-get install -y nodejs

# Install dependency kit for python
RUN pip install awscli virtualenv

# Install the serverless framework globally
RUN npm install -g serverless

# install docker client
RUN mkdir -p /tmp/docker-release \
 && curl -sSL https://download.docker.com/`uname -s | tr '[:upper:]' '[:lower:]'`/static/stable/`uname -m`/docker-17.06.0-ce.tgz | tar -zxf - -C /tmp/docker-release \
 && find /tmp/docker-release -name 'docker' -type f -perm '-u=x' -exec mv -i {} /usr/local/bin \; \
 && rm -rf /tmp/docker-release

# Set the same WORKDIR as default image
RUN mkdir /var/task
WORKDIR /var/task

ENTRYPOINT ["/bin/bash", "-c"]
