# Generated by Django 2.2 on 2019-04-17 05:27

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_icon',
            field=models.FileField(default='null.ico', max_length=200, upload_to=polls.models.make_filename),
        ),
    ]
